# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glcron < Formula
  desc "A TUI tool for managing GitLab CI/CD pipeline schedules"
  homepage "https://github.com/nikitasova/glcron"
  version "0.1.2-beta"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikitasova/glcron/releases/download/v0.1.2-beta/glcron_0.1.2-beta_darwin_amd64.tar.gz"
      sha256 "6e5bb4cd39330aafc29306122e82d7172080d1059c2a3d4d595070ca9885cd6b"

      def install
        bin.install "glcron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikitasova/glcron/releases/download/v0.1.2-beta/glcron_0.1.2-beta_darwin_arm64.tar.gz"
      sha256 "6396c0e3bfae5e4e94e6d08263e06b9a508a3230ad1922304d15cb61bd57df9b"

      def install
        bin.install "glcron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/glcron/releases/download/v0.1.2-beta/glcron_0.1.2-beta_linux_amd64.tar.gz"
      sha256 "48b16e181c3672846527fc1f0dd28e34be9ab4c2eee26a098b56800032b13bf7"
      def install
        bin.install "glcron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/glcron/releases/download/v0.1.2-beta/glcron_0.1.2-beta_linux_arm64.tar.gz"
      sha256 "e7db74317268990836bded4eac46f77ecacbdbd3f205158ca00e3aad71456264"
      def install
        bin.install "glcron"
      end
    end
  end

  test do
    system "#{bin}/glcron --version"
  end
end
