# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glcron < Formula
  desc "A TUI tool for managing GitLab CI/CD pipeline schedules"
  homepage "https://github.com/nikitasova/glcron"
  version "1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikitasova/glcron/releases/download/v1.4/glcron_1.4_darwin_amd64.tar.gz"
      sha256 "a8853e1713b49f267b5fd62f8f73ec5c8fb976d32384100531a222ac3300a49a"

      def install
        bin.install "glcron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikitasova/glcron/releases/download/v1.4/glcron_1.4_darwin_arm64.tar.gz"
      sha256 "177476a749c4d6c55350e87ba8cf142648408b2f56fafe00412b39cd72b28a1b"

      def install
        bin.install "glcron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/glcron/releases/download/v1.4/glcron_1.4_linux_amd64.tar.gz"
      sha256 "0e135b17d4b8c9efc2bb6a33fabeafc505da2808407ba2d2414db7a68721f1cc"
      def install
        bin.install "glcron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/glcron/releases/download/v1.4/glcron_1.4_linux_arm64.tar.gz"
      sha256 "a6d6d660dae808e5fcb7d966757f92a2cad62860cbe79c85c8bd972194b6b0e0"
      def install
        bin.install "glcron"
      end
    end
  end

  test do
    system "#{bin}/glcron --version"
  end
end
