# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glcron < Formula
  desc "A TUI tool for managing GitLab CI/CD pipeline schedules"
  homepage "https://github.com/nikitasova/glcron"
  version "1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikitasova/glcron/releases/download/v1.5/glcron_1.5_darwin_amd64.tar.gz"
      sha256 "b6848390675a329913441062b135e1fbdb06ccc20195994307d63837aa26e4d8"

      define_method(:install) do
        bin.install "glcron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikitasova/glcron/releases/download/v1.5/glcron_1.5_darwin_arm64.tar.gz"
      sha256 "906ab33ddc23e09908fa7e1e5920b38ab422bb88373b4bb0c7987f2e361b9ec0"

      define_method(:install) do
        bin.install "glcron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/glcron/releases/download/v1.5/glcron_1.5_linux_amd64.tar.gz"
      sha256 "3a8e19dce77075ccb64400c28cc5aed4ac854806a8df3c5e1899770f8b5c5b3c"
      define_method(:install) do
        bin.install "glcron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/glcron/releases/download/v1.5/glcron_1.5_linux_arm64.tar.gz"
      sha256 "407383dd63c05b8be1ea5fcf3b5bd11cefa605edd3d09edffeb818e7b4060e04"
      define_method(:install) do
        bin.install "glcron"
      end
    end
  end

  test do
    system "#{bin}/glcron --version"
  end
end
